code
Tahirbhalli/Testing-Jest pull request #1
Opened 2020-07-20 10:26 UTC by Tahirbhalli

This is a Testing Repo, where I Write tests with JEST.
for Run:
> npm run test

2020-07-20 15:11 UTC, whiz25 requested changes
## Changes Required :clap: 
You have done a great job setting up the project and writing the initial tests. We however need to make the following changes before we can merge.
- [x] add modules for ceaser cipher and array analysis
- [x] add tests for the above modules. make sure each module has it's own test file. For example, ceaser.js would have a test file as ceaser.test.js.
- [x] the index.test.js file contains tests for calculator.js and stringoperation.js modules. you need to split the file into calculator.test.js for calculator module and stringoperation.test.js for the stringoperation module.
- [x] add a title to this PR and a detailed description of what features this PR covers.

### Martin Afani

2020-07-21 06:51 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED

 Hi @Tahirbhalli good job working on this and kudos for making changes outlined by the previous reviewer :slightly_smiling_face:  please look into my comments below and try to make changes were appropriate :slightly_smiling_face:  

- Capitalize and  Caesar is currently failing and I have pointed out the reason below please make changes, modify your test, and submit for another review :slightly_smiling_face: 

Please submit for another review when you are done :slightly_smiling_face:  

**RAPHAEL NORIODE** :mask: stay_safe

2020-07-21 06:51 UTC, Oghenebrume50 commented on src/js/stringoperation.js
> +  const capitalize = (str) => str.toUpperCase();
Capitalize should make only the first character capital ![see](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/testing_practice/capitalize_requirement.png)

2020-07-21 06:51 UTC, Oghenebrume50 commented on src/js/ceaser.js
> +String.prototype.Ceaser = function (shift) {
The caser cipher function should take in the string and the shift as parameters, in order to test against multiple parameters this is the best way to implement it. 
Also you do not necessarily need to modify the String prototype, but if fine if you want to keep it that way :+1:

2020-07-21 15:28 UTC, shshamim63 approved these changes
## :1234: Approved
___
Hi @Tahirbhalli :wave: 
The tests are working fine. all of them are separated in different files, great job :clap: . But the function related to the array you were supposed to build is not covering the instruction. I am sorry that it was not mentioned earlier. So I am adding it as optional. Please check the comment below.
___
#### This :+1: is from me, you can go ahead.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-07-21 15:28 UTC, shshamim63 commented on src/js/Array.js
> +};
[optional]
You were supposed to create a function which takes an array as an input and returns an object like the following ->
Suppose the method name as arrayAnalysis and an array [1, 2, 3, 4, 5, 6]. So if you call arrayAnalysis([1, 2, 3, 4, 5, 6]) should return.
```js
{
    average: 3.50,
    min: 1,
    max: 6,
    length: 6,
}
```
I am really sorry this was not mentioned earlier.

2020-07-21 15:29 UTC, merged